version: "3"

services:
  monty_react:
    container_name: monty_react
    # build: ./Frontend/
    image: node:17-alpine3.14
    volumes:
      - ./Frontend/:/app
    ports:
      - "3000:3000"
    networks:
      - monty_network
    restart: on-failure
    # depends_on:
    #   - monty_django
    working_dir: /app
    command: bash -c "echo 'holaaaaaa'"

  monty_django:
    container_name: monty_django
    build: ./Backend/
    command: "python3 manage.py runserver "
    depends_on:
      - mysql_db

    working_dir: /app
    volumes:
      - ./Backend/:/app
    ports:
      - "8000:8000"
    networks:
      - monty_network


  mysql_db:
    container_name: monty_mysql

    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  monty_network: