# Generated by Django 3.1.14 on 2022-01-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20220119_1506'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('id_bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bike')),
                ('id_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
    ]
