# Generated by Django 3.1.14 on 2022-04-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={},
        ),
        migrations.RemoveField(
            model_name='credit',
            name='updated_at',
        ),
    ]
