# Generated by Django 3.1.14 on 2022-02-15 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0016_auto_20220208_2224'),
        ('profiles', '0006_auto_20220215_0108'),
        ('bikes', '0013_auto_20220204_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('checked', models.BooleanField(default=False)),
                ('admin_check', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_check', to='profiles.profile')),
                ('notif_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notif_user', to='profiles.profile')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reason', to='stations.point')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikes.register_bike')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
