# Generated by Django 3.1.14 on 2022-02-15 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20220215_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
