# Generated by Django 3.1.14 on 2022-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
