# Generated by Django 3.1.14 on 2022-01-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_bike_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='station',
        ),
    ]
