# Generated by Django 3.1.14 on 2022-01-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_auto_20220120_1518'),
        ('stations', '0004_auto_20220120_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bike', unique=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
