# Generated by Django 3.1.14 on 2022-02-15 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0013_auto_20220204_1531'),
        ('stations', '0016_auto_20220208_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='bike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='bikes.bike'),
        ),
    ]
