# Generated by Django 3.1.14 on 2022-02-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20220215_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.reason'),
        ),
    ]
