# Generated by Django 3.1.14 on 2022-02-15 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20220215_0255'),
        ('notifications', '0004_auto_20220215_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='admin_check',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_check', to='profiles.profile'),
        ),
    ]
