# Generated by Django 3.1.14 on 2022-02-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220215_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://avatars.dicebear.com/api/avataaars/QCPL0435D.svg'),
        ),
    ]
