# Generated by Django 3.1.14 on 2022-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20220419_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credit',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://avatars.dicebear.com/api/avataaars/MCRD6907I.svg'),
        ),
    ]
