# Generated by Django 3.1.14 on 2022-04-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        ('profiles', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_bike',
            name='point_get',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_get', to='stations.point'),
        ),
        migrations.AddField(
            model_name='register_bike',
            name='point_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_return', to='stations.point'),
        ),
        migrations.AddField(
            model_name='register_bike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.profile'),
        ),
    ]
