# Generated by Django 3.1.14 on 2022-01-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_remove_point_bike'),
        ('bikes', '0009_register_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', unique=True),
        ),
    ]
