# Generated by Django 3.1.14 on 2022-02-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220208_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://avatars.dicebear.com/api/avataaars/HNOJ9358P.svg'),
        ),
    ]
