# Generated by Django 3.1.14 on 2022-02-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20220215_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://avatars.dicebear.com/api/avataaars/FXGT2167A.svg'),
        ),
    ]
