# Generated by Django 3.1.14 on 2022-01-20 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_remove_bike_location'),
        ('stations', '0002_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
                ('id_bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bike')),
                ('id_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
