# Generated by Django 3.1.14 on 2022-01-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_remove_bike_location'),
        ('stations', '0003_auto_20220120_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bike'),
        ),
    ]
