# Generated by Django 3.1.14 on 2022-01-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_auto_20220121_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
