# Generated by Django 3.1.14 on 2022-01-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_auto_20220122_0424'),
        ('stations', '0008_auto_20220122_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id_bike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bike'),
        ),
    ]
