# Generated by Django 3.1.14 on 2022-01-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_auto_20220123_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='id_bike',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='id_station',
            new_name='station',
        ),
    ]
