# Generated by Django 3.1.14 on 2022-01-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_register_bike'),
        ('stations', '0010_auto_20220124_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='bikes.bike', unique=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='stations.station'),
        ),
    ]
