# Generated by Django 3.1.14 on 2022-01-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_auto_20220126_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='bike',
        ),
    ]
