# Generated by Django 3.1.14 on 2022-02-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_auto_20220126_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='stations/img/'),
        ),
    ]
